# Generated by Django 4.1.7 on 2023-03-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
