# Generated by Django 4.1.7 on 2023-03-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0002_alter_terrain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrain',
            name='complexeSportif',
        ),
        migrations.AddField(
            model_name='categoryterrain',
            name='complexeSportif',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Complexe.complexesportif'),
        ),
    ]
