# Generated by Django 4.1.7 on 2023-03-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0003_remove_terrain_complexesportif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='rank',
            field=models.IntegerField(default=None),
        ),
    ]
