# Generated by Django 4.1.7 on 2023-03-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0004_alter_terrain_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='rank',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
