# Generated by Django 4.1.7 on 2023-04-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0005_alter_terrain_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryterrain',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complexesportif',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='terrain',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrain',
            name='number_of_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
