# Generated by Django 4.1.7 on 2023-04-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0006_categoryterrain_area_complexesportif_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
