# Generated by Django 4.1.7 on 2023-04-09 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Complexe', '0007_alter_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_refused', models.BooleanField(default=False)),
                ('is_waiting', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_canceled_by_complex', models.BooleanField(default=False)),
                ('is_canceled_by_user', models.BooleanField(default=False)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complexe.terrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
