# Generated by Django 4.1.7 on 2023-04-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0008_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_canceled_by_complex',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_canceled_by_user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_refused',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_waiting',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
