# Generated by Django 4.1.7 on 2023-04-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0008_alter_terrain_is_reserved'),
        ('Complexe', '0009_remove_reservation_is_accepted_and_more'),
    ]

    operations = [
    ]
