# Generated by Django 4.1.7 on 2023-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0010_merge_20230409_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='endTime',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
