# Generated by Django 4.1.7 on 2023-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_rejected',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
