# Generated by Django 4.1.7 on 2023-04-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0013_reservation_approved_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_of_players_available',
        ),
    ]
