# Generated by Django 4.1.7 on 2023-04-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0015_remove_post_time_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_reservation',
        ),
        migrations.AddField(
            model_name='post',
            name='post_reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Complexe.reservation'),
        ),
    ]
