# Generated by Django 4.1.7 on 2023-05-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0019_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joined',
        ),
    ]
