# Generated by Django 4.1.7 on 2023-05-04 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Complexe', '0020_delete_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.CharField(default='Requested', max_length=100)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Complexe.reservation')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
