# Generated by Django 4.1.7 on 2023-05-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0021_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joined',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Complexe.post'),
        ),
    ]
