# Generated by Django 4.1.7 on 2023-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complexe', '0022_alter_joined_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexesportif',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
